name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x ]
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: Build
        run:
          go build -v  ./...